{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Import dependencies\n",
    "\n",
    "import json\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import re\n",
    "from sqlalchemy import create_engine\n",
    "from config import db_password\n",
    "import psycopg2\n",
    "import time\n",
    "import sqlalchemy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "'/Users/sonia_ij/Desktop/Data Analysis Class/Module 8/Movies_ETL/Data/filename'"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Define a variable for the directory that’s holding the data.\n",
    "file_dir = '/Users/sonia_ij/Desktop/Data Analysis Class/Module 8/Movies_ETL/Data/'\n",
    "f'{file_dir}filename'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# EXTRACT THE DATA\n",
    "\n",
    "# Create a function that takes in three arguments: Wikipedia data, Kaggle metadata, MovieLens rating data (from Kaggle)\n",
    "def Wiki_Kaggle_Ratings(wiki_movies_raw, kaggle_metadata, ratings):\n",
    "    \n",
    "    #Open Wikipedia file\n",
    "    with open (f'{file_dir}/wikipedia.movies.json', mode='r') as file:\n",
    "        wiki_movies_raw = json.load(file)\n",
    "    \n",
    "    # open kaggle file\n",
    "    kaggle_metadata = pd.read_csv(f'{file_dir}movies_metadata.csv', low_memory=False)  \n",
    "\n",
    "    #Open Movielens rating file\n",
    "    ratings = pd.read_csv(f'{file_dir}ratings.csv')\n",
    "\n",
    "    \n",
    "    # TRANSFORM THE DATA \n",
    "\n",
    "    # Inspect Wiki data\n",
    "    wiki_movies = [movie for movie in wiki_movies_raw\n",
    "                   if ('Director' in movie or 'Directed by' in movie)\n",
    "                       and 'imdb_link' in movie\n",
    "                       and 'No. of episodes' not in movie]\n",
    "\n",
    "    # Convert wiki_movies_raw into a DataFrame\n",
    "    wiki_movies_df = pd.DataFrame(wiki_movies_raw)\n",
    "\n",
    "    #Sort wiki columns\n",
    "    sorted(wiki_movies_df.columns.tolist())\n",
    "\n",
    "    def clean_movie(movie):\n",
    "        movie = dict(movie) #create a non-destructive copy\n",
    "        alt_titles = {}\n",
    "        # combine alternate titles into one list\n",
    "        for key in ['Also known as','Arabic','Cantonese','Chinese','French',\n",
    "                    'Hangul','Hebrew','Hepburn','Japanese','Literally',\n",
    "                    'Mandarin','McCune-Reischauer','Original title','Polish',\n",
    "                    'Revised Romanization','Romanized','Russian',\n",
    "                    'Simplified','Traditional','Yiddish']:\n",
    "            if key in movie:\n",
    "                alt_titles[key] = movie[key]\n",
    "                movie.pop(key)\n",
    "        if len(alt_titles) > 0:\n",
    "            movie['alt_titles'] = alt_titles\n",
    "\n",
    "        # merge column names\n",
    "        def change_column_name(old_name, new_name):\n",
    "            if old_name in movie:\n",
    "                movie[new_name] = movie.pop(old_name)\n",
    "        change_column_name('Adaptation by', 'Writer(s)')\n",
    "        change_column_name('Country of origin', 'Country')\n",
    "        change_column_name('Directed by', 'Director')\n",
    "        change_column_name('Distributed by', 'Distributor')\n",
    "        change_column_name('Edited by', 'Editor(s)')\n",
    "        change_column_name('Length', 'Running time')\n",
    "        change_column_name('Original release', 'Release date')\n",
    "        change_column_name('Music by', 'Composer(s)')\n",
    "        change_column_name('Produced by', 'Producer(s)')\n",
    "        change_column_name('Producer', 'Producer(s)')\n",
    "        change_column_name('Productioncompanies ', 'Production company(s)')\n",
    "        change_column_name('Productioncompany ', 'Production company(s)')\n",
    "        change_column_name('Released', 'Release Date')\n",
    "        change_column_name('Release Date', 'Release date')\n",
    "        change_column_name('Screen story by', 'Writer(s)')\n",
    "        change_column_name('Screenplay by', 'Writer(s)')\n",
    "        change_column_name('Story by', 'Writer(s)')\n",
    "        change_column_name('Theme music composer', 'Composer(s)')\n",
    "        change_column_name('Written by', 'Writer(s)')\n",
    "\n",
    "        return movie\n",
    "\n",
    "    #Rerun our list comprehension to clean wiki_movies and recreate wiki_movies_df\n",
    "    clean_movies = [clean_movie(movie) for movie in wiki_movies]\n",
    "    wiki_movies_df = pd.DataFrame(clean_movies)\n",
    "    try:\n",
    "        wiki_movies_df['imdb_id'] = wiki_movies_df['imdb_link'].str.extract(r'(tt\\d{7})')\n",
    "        wiki_movies_df.drop_duplicates(subset='imdb_id', inplace=True)\n",
    "    except:\n",
    "        print(f'\"encountered an error....proceeding\"')\n",
    "\n",
    "\n",
    "\n",
    "    # Check how many null values are in each column and keep any that are less than 90% null \n",
    "    wiki_columns_to_keep = [column for column in wiki_movies_df.columns if wiki_movies_df[column].isnull().sum() < len(wiki_movies_df) * 0.9]\n",
    "    wiki_movies_df = wiki_movies_df[wiki_columns_to_keep]\n",
    "\n",
    "    #Convert and Parse box office column \n",
    "    box_office = wiki_movies_df['Box office'].dropna() \\\n",
    "\n",
    "    # Make a separator string using apply method and then call the join() method on it.\n",
    "    box_office = box_office.apply(lambda x: ' '.join(x) if type(x) == list else x)\n",
    "\n",
    "    #Preface the string with an r for the escape characters to remain.\n",
    "    form_one = r'\\$\\d+\\.?\\d*\\s*[mb]illion'\n",
    "    box_office.str.contains(form_one, flags=re.IGNORECASE).sum()\n",
    "\n",
    "    # Preface the string with an r for the escape characters to remain.\n",
    "    form_two = r'\\$\\d{1,3}(?:,\\d{3})+'\n",
    "    box_office.str.contains(form_two, flags=re.IGNORECASE).sum()\n",
    "    \n",
    "    # Create two Boolean Series called matches_form_one and matches_form_two, and then select the box office values that don’t match either\n",
    "    matches_form_one = box_office.str.contains(form_one, flags=re.IGNORECASE)\n",
    "    matches_form_two = box_office.str.contains(form_two, flags=re.IGNORECASE)\n",
    "    box_office[~matches_form_one & ~matches_form_two]\n",
    "\n",
    "    # Now we need a function to turn the extracted values into a numeric value. We’ll call it parse_dollars\n",
    "    def parse_dollars(s):\n",
    "        # if s is not a string, return NaN\n",
    "        if type(s) != str:\n",
    "            return np.nan\n",
    "\n",
    "        # if input is of the form $###.# million\n",
    "        if re.match(r'\\$\\s*\\d+\\.?\\d*\\s*milli?on', s, flags=re.IGNORECASE):\n",
    "\n",
    "            # remove dollar sign and \" million\"\n",
    "            s = re.sub('\\$|\\s|[a-zA-Z]','', s)\n",
    "\n",
    "            # convert to float and multiply by a million\n",
    "            value = float(s) * 10**6\n",
    "\n",
    "            # return value\n",
    "            return value\n",
    "\n",
    "        # if input is of the form $###.# billion\n",
    "        elif re.match(r'\\$\\s*\\d+\\.?\\d*\\s*billi?on', s, flags=re.IGNORECASE):\n",
    "\n",
    "            # remove dollar sign and \" billion\"\n",
    "            s = re.sub('\\$|\\s|[a-zA-Z]','', s)\n",
    "\n",
    "            # convert to float and multiply by a billion\n",
    "            value = float(s) * 10**9\n",
    "\n",
    "            # return value\n",
    "            return value\n",
    "\n",
    "        # if input is of the form $###,###,###\n",
    "        elif re.match(r'\\$\\s*\\d{1,3}(?:[,\\.]\\d{3})+(?!\\s[mb]illion)', s, flags=re.IGNORECASE):\n",
    "\n",
    "            # remove dollar sign and commas\n",
    "            s = re.sub('\\$|,','', s)\n",
    "\n",
    "            # convert to float\n",
    "            value = float(s)\n",
    "\n",
    "            # return value\n",
    "            return value\n",
    "\n",
    "        # otherwise, return NaN\n",
    "        else:\n",
    "            return np.nan\n",
    "\n",
    "    #Parse box office values\n",
    "    wiki_movies_df['box_office'] = box_office.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)\n",
    "\n",
    "    # Drop the original box office column\n",
    "    wiki_movies_df.drop('Box office', axis=1, inplace=True)\n",
    "    \n",
    "    # Create a budget variable \n",
    "    budget = wiki_movies_df['Budget'].dropna()\n",
    "\n",
    "    # Convert any lists to strings\n",
    "    budget = budget.map(lambda x: ' '.join(x) if type(x) == list else x)\n",
    "\n",
    "    # Remove any values between a dollar sign and a hyphen (for budgets given in ranges)\n",
    "    budget = budget.str.replace(r'\\$.*[-—–](?![a-z])', '$', regex=True)\n",
    "\n",
    "    # Create two Boolean Series called matches_form_one and matches_form_two, \n",
    "    # and then select the budget values that don’t match either\n",
    "    matches_form_one = budget.str.contains(form_one, flags=re.IGNORECASE)\n",
    "    matches_form_two = budget.str.contains(form_two, flags=re.IGNORECASE)\n",
    "    budget[~matches_form_one & ~matches_form_two]\n",
    "\n",
    "    # Remove the citation references.\n",
    "    budget = budget.str.replace(r'\\[\\d+\\]\\s*', '')\n",
    "    budget[~matches_form_one & ~matches_form_two]\n",
    "\n",
    "    # parse the budget values.\n",
    "    wiki_movies_df['budget'] = budget.str.extract(f'({form_one}|{form_two})', flags=re.IGNORECASE)[0].apply(parse_dollars)\n",
    "\n",
    "    # Drop the original Budget columns.\n",
    "    wiki_movies_df.drop('Budget', axis=1, inplace=True)\n",
    "\n",
    "\n",
    "    # Make a variable that holds the non-null values of Release date in the DataFrame, converting lists to strings:\n",
    "    release_date = wiki_movies_df['Release date'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)\n",
    "\n",
    "    # One way to parse those forms is with the following:\n",
    "    date_form_one = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\\s[123]\\d,\\s\\d{4}'\n",
    "    date_form_two = r'\\d{4}.[01]\\d.[123]\\d'\n",
    "    date_form_three = r'(?:January|February|March|April|May|June|July|August|September|October|November|December)\\s\\d{4}'\n",
    "    date_form_four = r'\\d{4}'\n",
    "\n",
    "    # Extract the dates\n",
    "    release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})', flags=re.IGNORECASE)\n",
    "\n",
    "    # Use the to_datetime() method to set the infer_datetime_format option to True.\n",
    "    wiki_movies_df['release_date'] = pd.to_datetime(release_date.str.extract(f'({date_form_one}|{date_form_two}|{date_form_three}|{date_form_four})')[0], infer_datetime_format=True)\n",
    "\n",
    "    # Parse Running Time\n",
    "    running_time = wiki_movies_df['Running time'].dropna().apply(lambda x: ' '.join(x) if type(x) == list else x)\n",
    "\n",
    "    # Save extracted running time and convert to nans to 0. coerce makes errors NaNs. fillna() makes NaNs 0.\n",
    "    running_time_extract = running_time.str.extract(r'(\\d+)\\s*ho?u?r?s?\\s*(\\d*)|(\\d+)\\s*m')\n",
    "    running_time_extract = running_time_extract.apply(lambda col: pd.to_numeric(col, errors='coerce')).fillna(0)\n",
    "\n",
    "    # Use apply() to convert the hour capture groups and minute capture groups to minutes if the pure minutes capture group is zero, and save the output to wiki_movies_df\n",
    "    wiki_movies_df['running_time'] = running_time_extract.apply(lambda row: row[0]*60 + row[1] if row[2] == 0 else row[2], axis=1)\n",
    "\n",
    "    #Drop Running time from the dataset\n",
    "    wiki_movies_df.drop('Running time', axis=1, inplace=True)\n",
    "\n",
    "\n",
    "    #CLEAN THE KAGGLE DATA\n",
    "    # Remove the bad data\n",
    "    kaggle_metadata[~kaggle_metadata['adult'].isin(['True','False'])]\n",
    "\n",
    "    #keep rows where the adult column is False and drop the adult column.\n",
    "    kaggle_metadata = kaggle_metadata[kaggle_metadata['adult'] == 'False'].drop('adult',axis='columns')\n",
    "\n",
    "    # Convert and remove non-video from the kaggle DataFrame\n",
    "    kaggle_metadata['video'] == 'True'\n",
    "    kaggle_metadata['video'] = kaggle_metadata['video'] == 'True'\n",
    "\n",
    "    # Use the to_numeric() method from Pandas to convert colums, errors= argument is set to 'raise', to know if there’s any data that can’t be converted to numbers.\n",
    "    kaggle_metadata['budget'] = kaggle_metadata['budget'].astype(int)\n",
    "    kaggle_metadata['id'] = pd.to_numeric(kaggle_metadata['id'], errors='raise')\n",
    "    kaggle_metadata['popularity'] = pd.to_numeric(kaggle_metadata['popularity'], errors='raise')\n",
    "\n",
    "    # Convert release_date to datetime.\n",
    "    kaggle_metadata['release_date'] = pd.to_datetime(kaggle_metadata['release_date'])\n",
    "\n",
    "    # Reasonability Checks on Ratings Data\n",
    "\n",
    "    # Convert timestamp to datetime\n",
    "    ratings['timestamp'] = pd.to_datetime(ratings['timestamp'], unit='s')\n",
    "\n",
    "    # Merge DataFrames to identify redundant columns\n",
    "    movies_df = pd.merge(wiki_movies_df, kaggle_metadata, on='imdb_id', suffixes=['_wiki','_kaggle'])   \n",
    "\n",
    "    # We should investigate that wild outlier around 2006. We’re just going to choose some rough cutoff dates to single out that one movie. We’ll look for any movie whose release date according to Wikipedia is after 1996, but whose release date according to Kaggle is before 1965.\n",
    "    movies_df[(movies_df['release_date_wiki'] > '1996-01-01') & (movies_df['release_date_kaggle'] < '1965-01-01')]\n",
    "\n",
    "    # Get the index.\n",
    "    movies_df[(movies_df['release_date_wiki'] > '1996-01-01') & (movies_df['release_date_kaggle'] < '1965-01-01')].index\n",
    "\n",
    "    # Drop the row\n",
    "    movies_df = movies_df.drop(movies_df[(movies_df['release_date_wiki'] > '1996-01-01') & (movies_df['release_date_kaggle'] < '1965-01-01')].index)\n",
    "\n",
    "    # Drop the title_wiki, release_date_wiki, Language, and Production company(s) columns.\n",
    "    movies_df.drop(columns=['title_wiki','release_date_wiki','Language','Production company(s)'], inplace=True)\n",
    "\n",
    "    # Create a function that fills in missing data for a column pair and then drops the redundant column.\n",
    "    def fill_missing_kaggle_data(df, kaggle_column, wiki_column):\n",
    "        df[kaggle_column] = df.apply(\n",
    "            lambda row: row[wiki_column] if row[kaggle_column] == 0 else row[kaggle_column]\n",
    "            , axis=1)\n",
    "        df.drop(columns=wiki_column, inplace=True)\n",
    "\n",
    "    # Run the function for the three column pairs that we decided to fill in zeros.\n",
    "    fill_missing_kaggle_data(movies_df, 'runtime', 'running_time')\n",
    "    fill_missing_kaggle_data(movies_df, 'budget_kaggle', 'budget_wiki')\n",
    "    fill_missing_kaggle_data(movies_df, 'revenue', 'box_office')\n",
    "\n",
    "    # Reorder the columns \n",
    "    movies_df = movies_df.loc[:, ['imdb_id','id','title_kaggle','original_title','tagline','belongs_to_collection','url','imdb_link',\n",
    "                           'runtime','budget_kaggle','revenue','release_date_kaggle','popularity','vote_average','vote_count',\n",
    "                           'genres','original_language','overview','spoken_languages','Country',\n",
    "                           'production_companies','production_countries','Distributor',\n",
    "                           'Producer(s)','Director','Starring','Cinematography','Editor(s)','Writer(s)','Composer(s)','Based on'\n",
    "                          ]]\n",
    "\n",
    "    # Rename the columns to be consistent.\n",
    "    movies_df.rename({'id':'kaggle_id',\n",
    "                      'title_kaggle':'title',\n",
    "                      'url':'wikipedia_url',\n",
    "                      'budget_kaggle':'budget',\n",
    "                      'release_date_kaggle':'release_date',\n",
    "                      'Country':'country',\n",
    "                      'Distributor':'distributor',\n",
    "                      'Producer(s)':'producers',\n",
    "                      'Director':'director',\n",
    "                      'Starring':'starring',\n",
    "                      'Cinematography':'cinematography',\n",
    "                      'Editor(s)':'editors',\n",
    "                      'Writer(s)':'writers',\n",
    "                      'Composer(s)':'composers',\n",
    "                      'Based on':'based_on'\n",
    "                     }, axis='columns', inplace=True)\n",
    "\n",
    "    # TRANSFORM AND MERGE RATING DATA\n",
    "\n",
    "    #Rename the “userId” column to “count and ”pivot this data so that movieId is the index, the columns will be all the rating values, and the rows will be the counts for each rating value.\n",
    "    rating_counts = ratings.groupby(['movieId','rating'], as_index=False).count() \\\n",
    "                    .rename({'userId':'count'}, axis=1) \\\n",
    "                    .pivot(index='movieId',columns='rating', values='count')\n",
    "\n",
    "    # Rename the columns so they’re easier to understand.\n",
    "    rating_counts.columns = ['rating_' + str(col) for col in rating_counts.columns]\n",
    "\n",
    "    # Use a left merge, since we want to keep everything in movies_df:\\\n",
    "    movies_with_ratings_df = pd.merge(movies_df, rating_counts, left_on='kaggle_id', right_index=True, how='left')\n",
    "\n",
    "    # Replace NaNs with 0s Since not every movie got a rating for each rating level, there will be missing values instead of zeros.\n",
    "    movies_with_ratings_df[rating_counts.columns] = movies_with_ratings_df[rating_counts.columns].fillna(0)\n",
    "\n",
    "    # LOAD THE DATA\n",
    "    # Make a connection string for the local server.\n",
    "    db_string = f\"postgres://postgres:{db_password}@localhost:5432/movie_data\"\n",
    "\n",
    "    # Create the database engine \n",
    "    engine = create_engine(db_string)\n",
    "\n",
    "    # Delete movies table content in sql\n",
    "    movie_data = engine.connect()\n",
    "    truncate_query = sqlalchemy.text(\"TRUNCATE TABLE movies\")\n",
    "    movie_data.execution_options(autocommit=True).execute(truncate_query)\n",
    "    print('Removed content in movies sql table')\n",
    "\n",
    "    # Delete ratings table content in sql\n",
    "    movie_data = engine.connect()\n",
    "    truncate_query = sqlalchemy.text(\"TRUNCATE TABLE ratings\")\n",
    "    movie_data.execution_options(autocommit=True).execute(truncate_query)\n",
    "    print('Removed content in ratings sql table')\n",
    "\n",
    "    # Use the to_sql() method to save the movies_df DataFrame to a SQL table\n",
    "    movies_df.to_sql(name='movies', con=engine, if_exists='append')\n",
    "\n",
    "    # Save ratings to SQL\n",
    "    rows_imported = 0\n",
    "\n",
    "    # get the start_time from time.time()\n",
    "    start_time = time.time()\n",
    "    for data in pd.read_csv(f'{file_dir}ratings.csv', chunksize=1000000):\n",
    "\n",
    "        # print out the range of rows that are being imported\n",
    "        print(f'importing rows {rows_imported} to {rows_imported + len(data)}...', end='')\n",
    "        data.to_sql(name='ratings', con=engine, if_exists='append')\n",
    "        rows_imported += len(data)\n",
    "\n",
    "        # add elapsed time to final print out\n",
    "        print(f'Done. {time.time() - start_time} total seconds elapsed')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Competing data:\n",
    "# Wiki                     Movielens                Resolution\n",
    "#--------------------------------------------------------------------------\n",
    "# title_wiki               title_kaggle             Drop Wikipedia\n",
    "# running_time             runtime                  Keep Kaggle; fill in zeros with Wikipedia data.\n",
    "# budget_wiki              budget_kaggle            Keep Kaggle; fill in zeros with Wikipedia data.\n",
    "# box_office               revenue                  Keep Kaggle; fill in zeros with Wikipedia data.\n",
    "# release_date_wiki        release_date_kaggle      Drop Wikipedia.\n",
    "# Language                 original_language        Drop Wikipedia.\n",
    "# Production company(s)    production_companies     Drop Wikipedia."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Removed content in movies sql table\n",
      "Removed content in ratings sql table\n",
      "importing rows 0 to 1000000...Done. 147.85937213897705 total seconds elapsed\n",
      "importing rows 1000000 to 2000000...Done. 305.82801508903503 total seconds elapsed\n",
      "importing rows 2000000 to 3000000...Done. 453.9623441696167 total seconds elapsed\n",
      "importing rows 3000000 to 4000000...Done. 604.8779530525208 total seconds elapsed\n",
      "importing rows 4000000 to 5000000...Done. 752.3005042076111 total seconds elapsed\n",
      "importing rows 5000000 to 6000000...Done. 901.0226240158081 total seconds elapsed\n",
      "importing rows 6000000 to 7000000...Done. 1045.653230190277 total seconds elapsed\n",
      "importing rows 7000000 to 8000000...Done. 1187.646003961563 total seconds elapsed\n",
      "importing rows 8000000 to 9000000...Done. 1333.3396999835968 total seconds elapsed\n",
      "importing rows 9000000 to 10000000...Done. 1474.5165371894836 total seconds elapsed\n",
      "importing rows 10000000 to 11000000...Done. 1616.7675640583038 total seconds elapsed\n",
      "importing rows 11000000 to 12000000...Done. 1760.9983351230621 total seconds elapsed\n",
      "importing rows 12000000 to 13000000...Done. 1901.6507692337036 total seconds elapsed\n",
      "importing rows 13000000 to 14000000...Done. 2044.2755341529846 total seconds elapsed\n",
      "importing rows 14000000 to 15000000...Done. 2190.292932033539 total seconds elapsed\n",
      "importing rows 15000000 to 16000000...Done. 2337.6699030399323 total seconds elapsed\n",
      "importing rows 16000000 to 17000000...Done. 2483.284198284149 total seconds elapsed\n",
      "importing rows 17000000 to 18000000...Done. 2627.1242101192474 total seconds elapsed\n",
      "importing rows 18000000 to 19000000...Done. 2775.179707288742 total seconds elapsed\n",
      "importing rows 19000000 to 20000000...Done. 2914.9352281093597 total seconds elapsed\n",
      "importing rows 20000000 to 21000000...Done. 3058.2865080833435 total seconds elapsed\n",
      "importing rows 21000000 to 22000000...Done. 3199.4589009284973 total seconds elapsed\n",
      "importing rows 22000000 to 23000000...Done. 3340.064616918564 total seconds elapsed\n",
      "importing rows 23000000 to 24000000...Done. 3481.17813706398 total seconds elapsed\n",
      "importing rows 24000000 to 25000000...Done. 3623.235898256302 total seconds elapsed\n",
      "importing rows 25000000 to 26000000...Done. 3764.76682806015 total seconds elapsed\n",
      "importing rows 26000000 to 26024289...Done. 3768.095491170883 total seconds elapsed\n"
     ]
    }
   ],
   "source": [
    "Wiki_Kaggle_Ratings(\"wikipedia.movies.json\", \"movies_metadata.csv\", \"ratings.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
